### ISSUE TITLE
How change the wrong name of repo?

### ISSUE THREAD

**Issue by akserg** [devarchy/website#7]
Hi,

Thank you for your project.

I'm the owner of the **ng2-dnd** (https://github.com/akserg/ng2-dnd) project.  Someone added my project into your resource with the wrong name and url:

![image](https://cloud.githubusercontent.com/assets/1400409/22770186/3459ea1e-ee97-11e6-8894-e44ee93f2850.png)

Can we somehow fix it with right information:
- Name: ng2-dnd
- Npm repo: https://www.npmjs.com/package/ng2-dnd

Regards,
Sergey.

**Comment by brillout** [comment]
Hi,

Thanks for the nice library.

<br/>

Yes in your case adding the correct URLs to the same category should work.
I.e. add the entry (`https://github.com/akserg/ng2-dnd`, `https://www.npmjs.com/package/ng2-dnd`) to `Drag and Drop`.

<br/>

For future readers where both the GitHub URL and the npm URL is wrong;

You shouldn't directly add the entry with both corrected GitHub URL and npm URL. (Otherwise the library will end up having two entries.)

Instead following would work;

1. Add the entry with the correct GitHub URL and the old/current npm URL to the same category. I.e. add (`https://github.com/org/correct-name`, `https://www.npmjs.com/package/wrong-name`) to `Same Category`.
2. Add the entry with the correct GitHub URL and the correct npm URL to the same category. I.e. add (`https://github.com/org/correct-name`, `https://www.npmjs.com/package/correct-name`) to `Same Category`.

<br/>

Regards,
Romuald.

**Comment by brillout** [comment]
See previous answer.
